const Nft = [
  {
    image: "/images/nft01.png",
    name: "Into the future",
    price: "0.074 Eth",
    creator_name: "NFT Lady",
    creator_image: "/images/creator01.jpg",
    availability: "12 in stock",
    time: "341d : 3hr : 25m : 55s",
    likes: "1.2k",
  },
  // {
  //   image: "/images/nft02.png",
  //   name: "Naughty Ape",
  //   price: "0.080 Eth",
  //   creator_name: "NFT Queen",
  //   creator_image: "/images/creator04.jpg",
  //   availability: "7 in stock",
  //   time: "341d : 3hr : 25m : 55s",
  //   likes: "3.2k",
  // },
  {
    image: "/images/nft03.png",
    name: "Pretty Pussy",
    price: "0.044 Eth",
    creator_name: "Sussan Block",
    creator_image: "/images/creator02.jpg",
    availability: "12 in stock",
    time: "341d : 3hr : 25m : 55s",
    likes: "2.8k",
  },
  {
    image: "/images/nft08.png",
    name: "Fearsome Pussy",
    price: "0.077 Eth",
    creator_name: "Dora Martin",
    creator_image: "/images/creator06.jpg",
    availability: "10 in stock",
    time: "341d : 3hr : 25m : 55s",
    likes: "7.5k",
    category: "cat",
  },
  {
    image: "/images/nft07.png",
    name: "High Pussy",
    price: "0.040 Eth",
    creator_name: "John Lewis",
    creator_image: "/images/creator08.jpg",
    availability: "1 in stock",
    time: "341d : 3hr : 25m : 55s",
    likes: "1.2k",
  },
  {
    image: "/images/nft04.png",
    name: "Cool Cat",
    price: "0.064 Eth",
    creator_name: "Maria NFT",
    creator_image: "/images/creator03.jpg",
    availability: "9 in stock",
    time: "341d : 3hr : 25m : 55s",
    likes: "5k",
  },
  {
    image: "/images/nft05.png",
    name: "Just A Cat",
    price: "0.032 Eth",
    creator_name: "NFT Lady",
    creator_image: "/images/creator01.jpg",
    availability: "4 in stock",
    time: "341d : 3hr : 25m : 55s",
    likes: "1.2k",
  },
  {
    image: "/images/nft06.png",
    name: "Hippy Cat",
    price: "0.087 Eth",
    creator_name: "Lucy carr",
    creator_image: "/images/creator05.jpg",
    availability: "8 in stock",
    time: "341d : 3hr : 25m : 55s",
    likes: "12k",
  },
  {
    image: "/images/nft09.png",
    name: "Trendy Puss",
    price: "0.093 Eth",
    creator_name: "NFT Geek",
    creator_image: "/images/creator07.jpg",
    availability: "5 in stock",
    time: "341d : 3hr : 25m : 55s",
    likes: "10k",
    category: "cat",
  },
  {
    image: "/images/nft10.png",
    name: "Happy Monkey",
    price: "0.055 Eth",
    creator_name: "Rob Miro",
    creator_image: "/images/creator10.jpg",
    availability: "2 in stock",
    time: "341d : 3hr : 25m : 55s",
    likes: "2.2k",
    category: "cat",
  },
  {
    image: "/images/nft11.png",
    name: "Party Monkey",
    price: "0.077 Eth",
    creator_name: "Mark Demi",
    creator_image: "/images/creator09.jpg",
    availability: "7 in stock",
    time: "341d : 3hr : 25m : 55s",
    likes: "3.5k",
    category: "monkey",
  },
  {
    image: "/images/nft12.png",
    name: "The Cool Monkey",
    price: "0.074 Eth",
    creator_name: "NFT Lady",
    creator_image: "/images/creator01.jpg",
    availability: "11 in stock",
    time: "341d : 3hr : 25m : 55s",
    likes: "1k",
  },
  {
    image: "/images/nft13.png",
    name: "Sailor Monkey",
    price: "0.070 Eth",
    creator_name: "NFT Geek",
    creator_image: "/images/creator07.jpg",
    availability: "1 in stock",
    time: "341d : 3hr : 25m : 55s",
    likes: "8k",
  },
  {
    image: "/images/nft14.png",
    name: "Soldier Monkey",
    price: "0.035 Eth",
    creator_name: "Mark Demi",
    creator_image: "/images/creator09.jpg",
    availability: "9 in stock",
    time: "341d : 3hr : 25m : 55s",
    likes: "9.3k",
    category: "monkey",
  },
  {
    image: "/images/nft15.png",
    name: "Hippy Monkey",
    price: "0.065 Eth",
    creator_name: "John Lewis",
    creator_image: "/images/creator08.jpg",
    availability: "2 in stock",
    time: "341d : 3hr : 25m : 55s",
    likes: "5k",
    category: "monkey",
  },
  {
    image: "/images/nft16.jpg",
    name: "Serenity",
    price: "0.065 Eth",
    creator_name: "Mark Demi",
    creator_image: "/images/creator09.jpg",
    availability: "2 in stock",
    time: "341d : 3hr : 25m : 55s",
    likes: "5k",
    category: "abstract",
  },
  {
    image: "/images/nft17.png",
    name: "Digitalia",
    price: "0.052 Eth",
    creator_name: "Sussan Block",
    creator_image: "/images/creator02.jpg",
    availability: "2 in stock",
    time: "341d : 3hr : 25m : 55s",
    likes: "3k",
    category: "abstract",
  },
  {
    image: "/images/nft18.jpg",
    name: "Keeping balance",
    price: "0.089 Eth",
    creator_name: "Lucy Carr",
    creator_image: "/images/creator05.jpg",
    availability: "2 in stock",
    time: "341d : 3hr : 25m : 55s",
    likes: "2.8k",
    category: "abstract",
  },
];

export default Nft;
